const indexedDBAPIUnmatchedLinks='APIUnmatchedLinksDB'
const indexedDBAPIUnmatchedLinksVersion=1
const indexedDBUnmathcedLinksObject='objUnmatchedLinks'
const tableBody=document.querySelector('tbody')