const indexedDBControlledOrders='ControlledOrdersDB'
const indexedDBControlledOrdersVersion=1
const indexedDBControlledOrdersObject='objControlledOrders'
const indexedDBControlledOrdersIndexMain='timeStamp'
const indexedDBControlledOrdersIndex='timeStampIDX'
const tableBody=document.querySelector('tbody')